# -*- coding: utf-8 -*-
# Part of BrowseInfo. See LICENSE file for full copyright and licensing details.
from . import bed_transfer
from . import medical_appointment
from . import medical_appointment_consultation_line
from . import medical_appointment_line
from . import medical_inpatient_line
from . import medical_patient_medication
from . import medical_patient_medication1
from . import medical_family_disease
from . import medical_drug_route
from . import medical_inpatient_medication
from . import medical_inpatient_medication_transient
from . import medical_inpatient_registration
from . import medical_inpatient_update_note
from . import medical_insurance_plan
from . import medical_insurance
from . import medical_operation
from . import medical_operation_line
from . import medical_medication_dosage
from . import medical_medicament
from . import medical_dose_unit
from . import medical_patient_disease
from . import medical_patient_diseases
from . import medical_patient
from . import medical_physician
from . import res_company
from . import res_partner
from . import res_company
