# -*- coding: utf-8 -*-
# Part of BrowseInfo. See LICENSE file for full copyright and licensing details.
from . import res_company
from . import res_partner
from . import account_move
from . import bed_transfer
from . import medical_appointment
from . import medical_inp_update_note
from . import medical_appointment_line
from . import medical_appointment_consultation_line
from . import medical_inp_update_note_consultation_line
from . import medical_appointment_procedure
from . import medical_inpatient_procedure
from . import medical_inpatient_investigation
from . import medical_appointment_investigation
from . import medical_patient_line
from . import medical_inpatient_accommodation
from . import medical_inpatient_acc
from . import MedicalReportTemplate
from . import MedicalInvoiceTemplate
from . import medical_patient_medication
from . import medical_patient_medication1
from . import medical_drug_route
from . import medical_inpatient_medication
from . import medical_inpatient_medication_transient
from . import medical_inpatient_registration
from . import medical_insurance
from . import medical_operation
from . import medical_operation_line
from . import medical_lab
from . import medical_medication_dosage
from . import medical_medicament
from . import medical_dose_unit
from . import medical_patient
from . import medical_patient_attachment
from . import medical_physician
